version: "3.0"
services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    restart: always
    # volumes:
    #   - "./data/postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=helium_config_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  helium_config:
    image: hcs:latest
    container_name: helium_config
    ports:
      - "4000:4000"
      - "50051:50051"

